app:
  name: book-manage-server
  server:
    port: 9089
  deploy:
    version: 1.0

rpc:
  consumer:
    connectTimeout: 600000
    timeout: 600000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:29090/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/book_manage?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      initial-size: 5
      max-total: 10
      min-evictable-idle-time-millis: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

mybatis:
  mapper-locations: classpath*:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

image:
  #原图访问地址
  oriFileUrl: http://127.0.0.1/images_ori/
  #原图保存路径
  oriFileSavePath: /opt/nginx/library/images_ori/
  #缩略图保存路径
  thumbFileSavePath: /opt/nginx/library/images_thumb/
  #缩略图前缀
  thumbPrefix: _thumb
  #缩略图后缀
  thumbSuffix: png
  #图片缩放宽度，高度按照原图的比例获得
  thumbImageHeight: 80
